import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientBody from "./ClientBody";
import Script from "next/script";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        <Script
          crossOrigin="anonymous"
          src="//unpkg.com/same-runtime/dist/index.global.js"
        />
      </head>
      <body
        className="bg-gradient-to-b from-neutral-50 to-neutral-100 min-h-screen antialiased selection:bg-rose-100 selection:text-rose-900"
        style={{
          fontFamily: "var(--font-geist-sans), var(--font-geist-mono), sans-serif",
        }}
      >
        <div className="max-w-3xl mx-auto px-4 py-8">
          <ClientBody>{children}</ClientBody>
        </div>
      </body>
    </html>
  );
}
